spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rubies_fashion_store
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hien51035@gmail.com
    password: yohmegclgdpqmtzt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 0
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/
file:
  upload-dir: ./uploads/
logging:
  level:
    org:
      hibernate:
        type: trace